#--------------------------------
FROM node
WORKDIR /app
COPY package.json .
#Устанавливаем зависимости
RUN npm install
#Копируем наш текущий каталог в каталог докер контейнера /app
COPY . .
EXPOSE 3000
#Запускаем скрипт
CMD ["npm", "start"]